
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
spec:
  containers:
    - name: kubehelmjava
      image: cloudit101/centoskubectlhelmjdk8:latest
      command:
        - cat
      tty: true
